// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAJCaLbV8mJCivA9QctiMQ69JTo9an0pD8',
    appId: '1:949293406171:web:a73f8083ecc561a626f9fe',
    messagingSenderId: '949293406171',
    projectId: 'fir-f5a3f',
    authDomain: 'fir-f5a3f.firebaseapp.com',
    storageBucket: 'fir-f5a3f.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDGHnLp1Nj0WAZhwp8iPCr2a0D2ZLlAVbI',
    appId: '1:949293406171:android:fd84be941f2b926626f9fe',
    messagingSenderId: '949293406171',
    projectId: 'fir-f5a3f',
    storageBucket: 'fir-f5a3f.firebasestorage.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAJCaLbV8mJCivA9QctiMQ69JTo9an0pD8',
    appId: '1:949293406171:web:1e601922577a308d26f9fe',
    messagingSenderId: '949293406171',
    projectId: 'fir-f5a3f',
    authDomain: 'fir-f5a3f.firebaseapp.com',
    storageBucket: 'fir-f5a3f.firebasestorage.app',
  );
}
